### PR TITLE
Generate embed codes for direct links / binary files

### LINKED ISSUE #412: Embed codes for video URLs
Thank you for this great library. I have been using it for a long time now and I am very happy with it.

With version 3 it was possible to get embed codes for videos with a direct link (e.g. http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4), but this does not work anymore with version 4.

```
<video controls><source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"></video>
```

With version 4 I get a curl timeout exception. I do not think it is related to the endpoint, I tested it with various sources. I rather think it is related to the downloading of the response body which is probably not necessary here. I think in version 3 it stopped if a binary response was detected.

After some debugging I noticed in the changelog that support for files was removed. What was the reason to drop this? Would it be possible to add this again? And if it was to complex or something, would it be possible to throw an Exception when this is tried? Took me a bit to figure this out 🙂

### PR DESCRIPTION
**Pull request by digilist**
I tried to add support for embedding binary files via direct links (image, audio, videos). This fixes #412.

### CODE REVIEW

File: src/Http/CurlDispatcher.php [hunk 1]
```diff
@@ -102,6 +103,8 @@ private function __construct(array $settings, RequestInterface $request)
             CURLOPT_COOKIEFILE => $cookies,
             CURLOPT_HEADERFUNCTION => [$this, 'writeHeader'],
             CURLOPT_WRITEFUNCTION => [$this, 'writeBody'],
+            CURLOPT_NOPROGRESS => false,
```
Comment (oscarotero) [inline src/Http/CurlDispatcher.php:106]: Why add this option? According to php documentation, this should only be changed for debugging purposes only.

File: tests/cache/cdn2.thecatapi.com.images-cjd.jpg.php [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+        'Content-Location' => [
+            'https://cdn2.thecatapi.com/images/cjd.jpg'
+        ],
+        'X-Request-Time' => [
+            '0.048 ms'
+        ]
+    ],
+    'statusCode' => 200,
+    'reasonPhrase' => 'OK',
+    'body' => '����' . "\0" . 'JFIF' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '��' . "\0" . 'C' . "\0" . '	
```
Comment (oscarotero) [inline tests/cache/cdn2.thecatapi.com.images-cjd.jpg.php:75]: In theory, the response shouldn't contain any data in the body, if it's binary.

File: tests/fixtures/cdn2.thecatapi.com.images-cjd.jpg.php [hunk 3]
```diff
@@ -0,0 +1,31 @@
+<?php
+declare(strict_types = 1);
+
+return [
+    'authorName' => null,
+    'authorUrl' => null,
+    'cms' => null,
+    'code' => [
+        'html' => '<img src="https://cdn2.thecatapi.com/images/cjd.jpg"></img>',
```
Comment (oscarotero) [inline tests/fixtures/cdn2.thecatapi.com.images-cjd.jpg.php:9]: The `img` shouldn't have a closing tag

**Review by oscarotero — CHANGES_REQUESTED** [review]

File: src/Http/CurlDispatcher.php (hunk 1 above)
Comment (digilist) [reply src/Http/CurlDispatcher.php:106]: This is necessary for the progress function in the following line, otherwise it is not called.

File: tests/cache/cdn2.thecatapi.com.images-cjd.jpg.php (hunk 2 above)
Comment (digilist) [reply tests/cache/cdn2.thecatapi.com.images-cjd.jpg.php:75]: Wasn't sure about this either, but it's not the whole body and just the first bytes. Maybe the first data that is loaded before the progress function aborts loading further data.

File: tests/fixtures/cdn2.thecatapi.com.images-cjd.jpg.php (hunk 3 above)
Comment (digilist) [reply tests/fixtures/cdn2.thecatapi.com.images-cjd.jpg.php:9]: Ah, yes, you are right. I see the following options:
- adding an special case for `` to the `html()` function (my favorite)
- adding a `$selfClosing` parameter to the `html()` function
- replacing `></img>` in the generated html with ` />` (yeah, just kidding :smile:)
- generating the img tag directly without the `html()` function

What would you prefer?

Comment (oscarotero) [reply tests/fixtures/cdn2.thecatapi.com.images-cjd.jpg.php:9]: Yep, agree. I like the first option (the special case)

File: src/Http/CurlDispatcher.php (hunk 1 above)
Comment (oscarotero) [reply src/Http/CurlDispatcher.php:106]: I see.
In Embed 3.x I used the `write` callback for that (https://github.com/oscarotero/Embed/blob/v3.x/src/Http/CurlResult.php#L131) I think we can do the same here

Comment (digilist) [reply src/Http/CurlDispatcher.php]: Great, that works. Now the response body is also empty.

File: src/Http/CurlDispatcher.php [hunk 4]
```diff
@@ -187,6 +197,13 @@ private function writeBody($curl, $string): int
...
         }
 
+        if ($this->isBinary) {
+            fclose($this->body);
+            $this->body = null;
+
+            return -1;
+        }
+
         return fwrite($this->body, $string);
```
Comment (oscarotero) [inline src/Http/CurlDispatcher.php:207]: If we detect the response is binary we don't have to open a temporary stream in the first place.Something like this would be better:

```php
if ($this->isBinary) {
    return -1;
}

if (!$this->body) {
    $this->body = fopen('php://temp', 'w+');
}

return fwrite($this->body, $string);
```

**Review by oscarotero — CHANGES_REQUESTED** [review]

File: src/Http/CurlDispatcher.php (hunk 4 above)
Comment (digilist) [reply src/Http/CurlDispatcher.php]: You are absolutely right, must have overlooked this. Thank you!

**Review by oscarotero — APPROVED** [review]

**Comment by oscarotero** [comment]
Sorry, I forgot this.
Merged. Thank you!

**Comment by digilist** [comment]
No worries, I only fixed your last comment today :wink: I did not receive an email from GitHub and missed this somehow.

Thank you very much for your quick responses and support 😊
